Repository bmcmanus-apex/mergify_poc, pull requests merged in 2023-02, with the labels that each got.

#9 Update docs WRT queues
  README.md
Labels: automerge

#12 Add linting workflow
  .github/mergify.yml
  .github/workflows/doc-linter.yaml
  README.md
Labels: do-not-merge

#19 Add sleep to CI
  .github/workflows/doc-linter.yaml
Labels: automerge

#24 Add push to ci
  .github/workflows/doc-linter.yaml
Labels: automerge

#36 ci(Mergify): configuration update
  .github/mergify.yml
Labels: automerge

#33 Jump queue with hotfix
  README.md
Labels: hotfix

#53 Stale
  TEST_MARKDOWN.md
Labels: stale

#63 Run linter on PR only
  .github/workflows/doc-linter.yaml
Labels: team:platform-dev-exp

#64 ci(Mergify): configuration update
  .github/mergify.yml
Labels: team:platform-dev-exp

#65 Add PR template
  .github/workflows/PULL_REQUEST_TEMPLATE/checklist.md
Labels: automerge, team:platform-dev-exp

#76 DEMO-CONFLICT1
  .github/workflows/doc-linter.yaml
Labels: team:platform-dev-exp

#84 DEMO-FIRST
  README.md
Labels: automerge

#81 DEMO-HOTFIX
  TEST_MARKDOWN.md
Labels: hotfix

#82 DEMO-CONFLICT1
  .github/workflows/doc-linter.yaml
Labels: team:platform-dev-exp
